export type NutritionTotals = {
  calories: number
  protein: number
  carbs: number
  fat: number
}

export type NutritionBasis = 'piece' | '100g' | 'cup' | 'tbsp' | 'tsp' | '100ml'

export type IngredientCategory =
  | 'proteins'
  | 'grains_starches'
  | 'vegetables'
  | 'legumes'
  | 'fruits'
  | 'dairy'
  | 'oils_sauces'
  | 'herbs_spices'
  | 'nuts_seeds'
  | 'baking'
  | 'beverages'
  | 'other'

export type IngredientNutrition = NutritionTotals & {
  basis: NutritionBasis
}

export type IngredientCatalogEntry = {
  category: IngredientCategory
  nutrition: IngredientNutrition
}

const LEGACY_INGREDIENT_NUTRITION: Record<string, IngredientNutrition> = {
  egg: { basis: 'piece', calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3 },
  eggs: { basis: 'piece', calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3 },
  banana: { basis: 'piece', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  plantain: { basis: 'piece', calories: 218, protein: 2, carbs: 57, fat: 0.5 },
  'green plantain': { basis: 'piece', calories: 180, protein: 1.8, carbs: 47, fat: 0.5 },
  'ripe plantain': { basis: 'piece', calories: 230, protein: 2.3, carbs: 61, fat: 0.6 },
  apple: { basis: 'piece', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  tomato: { basis: 'piece', calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },
  onion: { basis: 'piece', calories: 44, protein: 1.2, carbs: 10.3, fat: 0.1 },
  garlic: { basis: 'piece', calories: 4, protein: 0.2, carbs: 1, fat: 0 },
  ginger: { basis: 'piece', calories: 5, protein: 0.1, carbs: 1.1, fat: 0 },
  carrot: { basis: 'piece', calories: 25, protein: 0.6, carbs: 6, fat: 0.1 },
  potato: { basis: 'piece', calories: 161, protein: 4.3, carbs: 37, fat: 0.2 },
  'sweet potato': { basis: 'piece', calories: 112, protein: 2, carbs: 26, fat: 0.1 },
  cassava: { basis: '100g', calories: 160, protein: 1.4, carbs: 38.1, fat: 0.3 },
  breadfruit: { basis: '100g', calories: 103, protein: 1.1, carbs: 27.1, fat: 0.2 },
  cucumber: { basis: 'piece', calories: 8, protein: 0.3, carbs: 1.9, fat: 0.1 },
  'bok choy': { basis: 'cup', calories: 9, protein: 1.1, carbs: 1.5, fat: 0.1 },
  'napa cabbage': { basis: 'cup', calories: 13, protein: 1, carbs: 2.4, fat: 0.2 },
  callaloo: { basis: 'cup', calories: 35, protein: 3, carbs: 6, fat: 0.3 },
  'bell pepper': { basis: 'piece', calories: 24, protein: 1, carbs: 6, fat: 0.2 },
  arepa: { basis: 'piece', calories: 180, protein: 4.2, carbs: 36, fat: 2.2 },
  'precooked corn flour': { basis: 'cup', calories: 440, protein: 8.5, carbs: 92, fat: 2.4 },
  bread: { basis: 'piece', calories: 80, protein: 3, carbs: 15, fat: 1 },
  baguette: { basis: 'piece', calories: 160, protein: 5, carbs: 32, fat: 0.8 },
  'sourdough bread': { basis: 'piece', calories: 120, protein: 4, carbs: 23, fat: 1.2 },
  tortilla: { basis: 'piece', calories: 140, protein: 4, carbs: 24, fat: 3.5 },
  avocado: { basis: 'piece', calories: 240, protein: 3, carbs: 12.8, fat: 22 },
  chicken: { basis: '100g', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  'chicken breast': { basis: '100g', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  'chicken thigh': { basis: '100g', calories: 209, protein: 26, carbs: 0, fat: 10.9 },
  'jerk chicken': { basis: '100g', calories: 220, protein: 27, carbs: 2, fat: 11 },
  beef: { basis: '100g', calories: 250, protein: 26, carbs: 0, fat: 15 },
  'beef steak': { basis: '100g', calories: 271, protein: 25, carbs: 0, fat: 19 },
  'skirt steak': { basis: '100g', calories: 273, protein: 24, carbs: 0, fat: 19.2 },
  'ground beef': { basis: '100g', calories: 332, protein: 14, carbs: 0, fat: 30 },
  pork: { basis: '100g', calories: 242, protein: 27, carbs: 0, fat: 14 },
  'pork loin': { basis: '100g', calories: 206, protein: 27, carbs: 0, fat: 10.7 },
  'pork chop': { basis: '100g', calories: 231, protein: 24.5, carbs: 0, fat: 14.8 },
  'pork ribs': { basis: '100g', calories: 292, protein: 18.5, carbs: 0, fat: 24 },
  bacon: { basis: '100g', calories: 541, protein: 37, carbs: 1.4, fat: 42 },
  sausage: { basis: '100g', calories: 301, protein: 12, carbs: 2, fat: 27 },
  ham: { basis: '100g', calories: 145, protein: 21, carbs: 1.5, fat: 5.5 },
  oxtail: { basis: '100g', calories: 262, protein: 30, carbs: 0, fat: 15 },
  'goat meat': { basis: '100g', calories: 143, protein: 27, carbs: 0, fat: 3 },
  saltfish: { basis: '100g', calories: 105, protein: 23, carbs: 0, fat: 0.9 },
  salmon: { basis: '100g', calories: 208, protein: 20, carbs: 0, fat: 13 },
  tuna: { basis: '100g', calories: 132, protein: 28, carbs: 0, fat: 1.3 },
  shrimp: { basis: '100g', calories: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  cheese: { basis: '100g', calories: 402, protein: 25, carbs: 1.3, fat: 33 },
  'fresh cheese': { basis: '100g', calories: 264, protein: 18, carbs: 4, fat: 20 },
  parmesan: { basis: '100g', calories: 431, protein: 38, carbs: 4.1, fat: 29 },
  mozzarella: { basis: '100g', calories: 280, protein: 28, carbs: 3.1, fat: 17 },
  cheddar: { basis: '100g', calories: 403, protein: 25, carbs: 1.3, fat: 33 },
  ricotta: { basis: '100g', calories: 174, protein: 11.3, carbs: 3, fat: 13 },
  rice: { basis: 'cup', calories: 206, protein: 4.3, carbs: 45, fat: 0.4 },
  'white rice': { basis: 'cup', calories: 206, protein: 4.3, carbs: 45, fat: 0.4 },
  'brown rice': { basis: 'cup', calories: 216, protein: 5, carbs: 45, fat: 1.8 },
  'jasmine rice': { basis: 'cup', calories: 205, protein: 4.3, carbs: 45, fat: 0.4 },
  'sticky rice': { basis: 'cup', calories: 169, protein: 3.5, carbs: 36.7, fat: 0.3 },
  pasta: { basis: 'cup', calories: 221, protein: 8, carbs: 43, fat: 1.3 },
  spaghetti: { basis: 'cup', calories: 221, protein: 8, carbs: 43, fat: 1.3 },
  penne: { basis: 'cup', calories: 220, protein: 8, carbs: 43, fat: 1.3 },
  gnocchi: { basis: 'cup', calories: 250, protein: 6, carbs: 53, fat: 1.2 },
  quinoa: { basis: 'cup', calories: 222, protein: 8.1, carbs: 39.4, fat: 3.6 },
  oats: { basis: 'cup', calories: 307, protein: 10.7, carbs: 54.8, fat: 5.3 },
  flour: { basis: 'cup', calories: 455, protein: 13, carbs: 95, fat: 1.2 },
  milk: { basis: 'cup', calories: 103, protein: 8, carbs: 12, fat: 2.4 },
  'coconut milk': { basis: 'cup', calories: 445, protein: 4.6, carbs: 6.4, fat: 48 },
  cream: { basis: 'cup', calories: 821, protein: 4.9, carbs: 6.6, fat: 88 },
  yogurt: { basis: 'cup', calories: 149, protein: 13, carbs: 11.4, fat: 8 },
  broccoli: { basis: 'cup', calories: 55, protein: 3.7, carbs: 11.2, fat: 0.6 },
  spinach: { basis: 'cup', calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1 },
  lettuce: { basis: 'cup', calories: 5, protein: 0.5, carbs: 1, fat: 0.1 },
  mushroom: { basis: 'cup', calories: 15, protein: 2.2, carbs: 2.3, fat: 0.2 },
  'shiitake mushrooms': { basis: 'cup', calories: 81, protein: 2.3, carbs: 21.4, fat: 0.3 },
  'enoki mushrooms': { basis: 'cup', calories: 24, protein: 1.7, carbs: 5, fat: 0.2 },
  'green onion': { basis: 'cup', calories: 32, protein: 1.8, carbs: 7.3, fat: 0.2 },
  corn: { basis: 'cup', calories: 96, protein: 3.4, carbs: 21, fat: 1.5 },
  beans: { basis: 'cup', calories: 127, protein: 8.7, carbs: 22.8, fat: 0.5 },
  'black beans': { basis: 'cup', calories: 132, protein: 8.9, carbs: 23.7, fat: 0.5 },
  chickpeas: { basis: 'cup', calories: 269, protein: 14.5, carbs: 45, fat: 4.2 },
  lentils: { basis: 'cup', calories: 230, protein: 17.9, carbs: 39.9, fat: 0.8 },
  'red beans': { basis: 'cup', calories: 225, protein: 15.4, carbs: 40.4, fat: 0.9 },
  'pigeon peas': { basis: 'cup', calories: 170, protein: 11.5, carbs: 30.9, fat: 0.9 },
  peas: { basis: 'cup', calories: 134, protein: 8.6, carbs: 25, fat: 0.4 },
  butter: { basis: 'tbsp', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 },
  'olive oil': { basis: 'tbsp', calories: 119, protein: 0, carbs: 0, fat: 13.5 },
  oil: { basis: 'tbsp', calories: 119, protein: 0, carbs: 0, fat: 13.5 },
  sugar: { basis: 'tbsp', calories: 49, protein: 0, carbs: 12.6, fat: 0 },
  honey: { basis: 'tbsp', calories: 64, protein: 0.1, carbs: 17.3, fat: 0 },
  'soy sauce': { basis: 'tbsp', calories: 9, protein: 1.3, carbs: 0.8, fat: 0.1 },
  'sesame oil': { basis: 'tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
  mirin: { basis: 'tbsp', calories: 35, protein: 0, carbs: 8, fat: 0 },
  sake: { basis: '100ml', calories: 134, protein: 0.5, carbs: 5, fat: 0 },
  miso: { basis: 'tbsp', calories: 34, protein: 2.2, carbs: 4.3, fat: 1.2 },
  'dark soy sauce': { basis: 'tbsp', calories: 11, protein: 1.5, carbs: 1.1, fat: 0 },
  gochujang: { basis: 'tbsp', calories: 33, protein: 0.9, carbs: 7.2, fat: 0.5 },
  kimchi: { basis: 'cup', calories: 23, protein: 1.6, carbs: 4, fat: 0.9 },
  'curry paste': { basis: 'tbsp', calories: 25, protein: 0.5, carbs: 3, fat: 1.2 },
  salt: { basis: 'tsp', calories: 0, protein: 0, carbs: 0, fat: 0 },
  pepper: { basis: 'tsp', calories: 6, protein: 0.2, carbs: 1.4, fat: 0.1 },
  water: { basis: '100ml', calories: 0, protein: 0, carbs: 0, fat: 0 },
  juice: { basis: '100ml', calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2 },
  broth: { basis: '100ml', calories: 6, protein: 0.5, carbs: 0.4, fat: 0.2 },
  'ramen noodles': { basis: 'cup', calories: 371, protein: 10.8, carbs: 52, fat: 13.3 },
  dumplings: { basis: 'cup', calories: 250, protein: 10, carbs: 30, fat: 9 },
  'udon noodles': { basis: 'cup', calories: 210, protein: 6.5, carbs: 43, fat: 0.6 },
  'soba noodles': { basis: 'cup', calories: 113, protein: 5.8, carbs: 24.3, fat: 0.1 },
  'rice noodles': { basis: 'cup', calories: 192, protein: 3.2, carbs: 44.8, fat: 0.4 },
  gyoza: { basis: 'cup', calories: 240, protein: 11, carbs: 28, fat: 9 },
  wonton: { basis: 'cup', calories: 257, protein: 11.3, carbs: 28.3, fat: 10.8 },
  tofu: { basis: '100g', calories: 76, protein: 8, carbs: 1.9, fat: 4.8 },
}

const categoryProfiles: Record<IngredientCategory, IngredientNutrition> = {
  proteins: { basis: '100g', calories: 205, protein: 22, carbs: 0.6, fat: 12 },
  grains_starches: { basis: 'cup', calories: 210, protein: 6.5, carbs: 41, fat: 2.2 },
  vegetables: { basis: 'cup', calories: 35, protein: 2.1, carbs: 6.8, fat: 0.4 },
  legumes: { basis: 'cup', calories: 220, protein: 14.2, carbs: 37.5, fat: 2.6 },
  fruits: { basis: 'piece', calories: 85, protein: 1, carbs: 21, fat: 0.4 },
  dairy: { basis: '100g', calories: 180, protein: 10, carbs: 6, fat: 12 },
  oils_sauces: { basis: 'tbsp', calories: 70, protein: 0.8, carbs: 4.1, fat: 5.5 },
  herbs_spices: { basis: 'tsp', calories: 5, protein: 0.2, carbs: 1, fat: 0.1 },
  nuts_seeds: { basis: '100g', calories: 560, protein: 19, carbs: 20, fat: 48 },
  baking: { basis: 'cup', calories: 360, protein: 8, carbs: 76, fat: 3.5 },
  beverages: { basis: '100ml', calories: 28, protein: 0.4, carbs: 6.4, fat: 0.1 },
  other: { basis: 'piece', calories: 40, protein: 2, carbs: 4, fat: 1 },
}

function createEntries(
  category: IngredientCategory,
  names: string[],
  overrides: Record<string, Partial<IngredientNutrition>> = {}
): Record<string, IngredientCatalogEntry> {
  const profile = categoryProfiles[category]
  return Object.fromEntries(
    names.map((name) => [
      name,
      {
        category,
        nutrition: {
          ...profile,
          ...(overrides[name] ?? {}),
        } as IngredientNutrition,
      },
    ])
  )
}

function inferLegacyCategory(key: string): IngredientCategory {
  if (/oil|sauce|miso|gochujang|mirin|salt|pepper|sugar|honey|butter|curry paste/.test(key)) {
    return 'oils_sauces'
  }
  if (/rice|pasta|noodles|flour|bread|tortilla|oats|quinoa|gnocchi|arepa/.test(key)) {
    return 'grains_starches'
  }
  if (/chicken|beef|pork|bacon|sausage|ham|oxtail|goat|saltfish|salmon|tuna|shrimp|egg|tofu/.test(key)) {
    return 'proteins'
  }
  if (/milk|cheese|parmesan|mozzarella|cheddar|ricotta|cream|yogurt/.test(key)) {
    return 'dairy'
  }
  if (/beans|peas|chickpeas|lentils/.test(key)) {
    return 'legumes'
  }
  if (/banana|plantain|apple|avocado/.test(key)) {
    return 'fruits'
  }
  if (/juice|water|broth|sake/.test(key)) {
    return 'beverages'
  }
  if (/tomato|onion|garlic|ginger|carrot|potato|cassava|breadfruit|cucumber|choy|cabbage|callaloo|pepper|broccoli|spinach|lettuce|mushroom|corn|green onion|kimchi/.test(key)) {
    return 'vegetables'
  }
  return 'other'
}

const additionalCatalog: Record<string, IngredientCatalogEntry> = {
  ...createEntries('proteins', [
    'whole chicken',
    'turkey',
    'turkey breast',
    'ground turkey',
    'duck',
    'lamb',
    'lamb chops',
    'lamb shoulder',
    'veal',
    'pork belly',
    'pork shoulder',
    'pork tenderloin',
    'beef chuck',
    'beef brisket',
    'beef short ribs',
    'beef shank',
    'beef liver',
    'chorizo',
    'prosciutto',
    'anchovy',
    'sardine',
    'mackerel',
    'cod',
    'tilapia',
    'trout',
    'halibut',
    'catfish',
    'snapper',
    'grouper',
    'crab',
    'lobster',
    'mussels',
    'clams',
    'squid',
    'octopus',
    'scallops',
    'tempeh',
    'seitan',
    'edamame',
    'paneer',
    'egg whites',
    'egg yolk',
  ], {
    turkey: { calories: 189, protein: 29, fat: 7.4, carbs: 0 },
    cod: { calories: 82, protein: 18, fat: 0.7, carbs: 0 },
    tilapia: { calories: 96, protein: 20.1, fat: 1.7, carbs: 0 },
    tempeh: { calories: 193, protein: 20.3, fat: 10.8, carbs: 7.6 },
    'whole chicken': { calories: 215, protein: 18, fat: 15, carbs: 0 },
    'pork belly': { calories: 518, protein: 9.3, fat: 53, carbs: 0 },
  }),
  ...createEntries('grains_starches', [
    'basmati rice',
    'wild rice',
    'arborio rice',
    'short grain rice',
    'long grain rice',
    'red rice',
    'black rice',
    'barley',
    'farro',
    'bulgur',
    'couscous',
    'millet',
    'amaranth',
    'freekeh',
    'sorghum',
    'buckwheat',
    'polenta',
    'cornmeal',
    'semolina',
    'noodles',
    'egg noodles',
    'lasagna sheets',
    'macaroni',
    'fusilli',
    'farfalle',
    'orzo',
    'linguine',
    'fettuccine',
    'vermicelli',
    'angel hair pasta',
    'naan',
    'pita bread',
    'flatbread',
    'bagel',
    'corn tortilla',
    'flour tortilla',
    'masa harina',
    'cornstarch',
    'rice flour',
    'whole wheat flour',
    'all purpose flour',
    'sweet potatoes',
    'potatoes',
    'yuca',
    'taro',
  ], {
    'basmati rice': { calories: 210, protein: 4.4, carbs: 45, fat: 0.5 },
    'sweet potatoes': { basis: 'piece', calories: 112, protein: 2, carbs: 26, fat: 0.1 },
    potatoes: { basis: 'piece', calories: 161, protein: 4.3, carbs: 37, fat: 0.2 },
    yuca: { basis: '100g', calories: 160, protein: 1.4, carbs: 38.1, fat: 0.3 },
    'yucca root': { basis: '100g', calories: 160, protein: 1.4, carbs: 38.1, fat: 0.3 },
  }),
  ...createEntries('vegetables', [
    'shallot',
    'leek',
    'red onion',
    'yellow onion',
    'white onion',
    'chives',
    'celery',
    'celery root',
    'fennel',
    'bok choy leaves',
    'cauliflower',
    'cabbage',
    'red cabbage',
    'green cabbage',
    'savoy cabbage',
    'brussels sprouts',
    'asparagus',
    'green beans',
    'snap peas',
    'sugar snap peas',
    'okra',
    'eggplant',
    'zucchini',
    'yellow squash',
    'butternut squash',
    'acorn squash',
    'pumpkin',
    'beet',
    'radish',
    'turnip',
    'parsnip',
    'rutabaga',
    'kale',
    'swiss chard',
    'collard greens',
    'mustard greens',
    'arugula',
    'romaine lettuce',
    'jalapeno',
    'serrano pepper',
    'habanero pepper',
    'poblano pepper',
    'bell peppers',
    'cherry tomato',
    'roma tomato',
    'sun dried tomato',
    'artichoke',
    'hearts of palm',
    'watercress',
    'bean sprouts',
    'bamboo shoots',
    'lotus root',
  ]),
  ...createEntries('legumes', [
    'pinto beans',
    'kidney beans',
    'navy beans',
    'cannellini beans',
    'great northern beans',
    'fava beans',
    'lima beans',
    'adzuki beans',
    'mung beans',
    'soybeans',
    'split peas',
    'green lentils',
    'red lentils',
    'brown lentils',
    'black lentils',
    'beluga lentils',
    'yellow lentils',
    'black eyed peas',
    'cowpeas',
    'garbanzo beans',
    'white beans',
    'cranberry beans',
    'borlotti beans',
    'butter beans',
  ], {
    'pinto beans': { calories: 245, protein: 15.4, carbs: 44.8, fat: 1.1 },
    'kidney beans': { calories: 225, protein: 15.3, carbs: 40.4, fat: 0.9 },
  }),
  ...createEntries('fruits', [
    'orange',
    'mandarin',
    'tangerine',
    'grapefruit',
    'lemon',
    'lime',
    'berries',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'cranberry',
    'cherry',
    'grape',
    'pear',
    'peach',
    'nectarine',
    'plum',
    'apricot',
    'kiwi',
    'mango',
    'papaya',
    'pineapple',
    'guava',
    'passion fruit',
    'dragon fruit',
    'lychee',
    'durian',
    'jackfruit',
    'fig',
    'date',
    'pomegranate',
    'watermelon',
    'cantaloupe',
    'honeydew',
    'coconut',
    'plantains',
    'green banana',
    'ripe banana',
    'soursop',
    'starfruit',
    'persimmon',
    'mulberry',
    'currants',
    'gooseberry',
  ], {
    mango: { calories: 99, protein: 1.4, carbs: 25, fat: 0.6 },
    pineapple: { calories: 83, protein: 0.9, carbs: 22, fat: 0.2 },
    avocado: { calories: 240, protein: 3, carbs: 12.8, fat: 22 },
  }),
  ...createEntries('dairy', [
    'whole milk',
    'skim milk',
    'evaporated milk',
    'condensed milk',
    'almond milk',
    'soy milk',
    'oat milk',
    'goat milk',
    'kefir',
    'greek yogurt',
    'plain yogurt',
    'sour cream',
    'creme fraiche',
    'heavy cream',
    'half and half',
    'cream cheese',
    'cottage cheese',
    'feta',
    'goat cheese',
    'blue cheese',
    'gouda',
    'swiss cheese',
    'monterey jack',
    'pepper jack',
    'provolone',
    'brie',
    'camembert',
    'halloumi',
    'paneer cheese',
    'mascarpone',
    'labneh',
    'ghee',
    'ice cream',
  ], {
    milk: { basis: 'cup', calories: 103, protein: 8, carbs: 12, fat: 2.4 },
    butter: { basis: 'tbsp', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 },
    ghee: { basis: 'tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
    yogurt: { basis: 'cup', calories: 149, protein: 13, carbs: 11.4, fat: 8 },
  }),
  ...createEntries('oils_sauces', [
    'vegetable oil',
    'canola oil',
    'sunflower oil',
    'coconut oil',
    'avocado oil',
    'grapeseed oil',
    'peanut oil',
    'corn oil',
    'palm oil',
    'lard',
    'beef tallow',
    'fish sauce',
    'oyster sauce',
    'tamari',
    'light soy sauce',
    'sweet soy sauce',
    'hoisin sauce',
    'black bean sauce',
    'chili oil',
    'sriracha',
    'harissa',
    'sambal oelek',
    'red curry paste',
    'green curry paste',
    'yellow curry paste',
    'tomato paste',
    'tomato sauce',
    'ketchup',
    'mustard',
    'mayonnaise',
    'vinaigrette',
    'balsamic vinegar',
    'apple cider vinegar',
    'rice vinegar',
    'worcestershire sauce',
    'hot sauce',
    'barbecue sauce',
    'teriyaki sauce',
    'ponzu',
    'tahini',
    'mole paste',
    'annatto paste',
    'coconut aminos',
    'salsa verde',
    'chipotle sauce',
  ], {
    'vegetable oil': { calories: 119, protein: 0, carbs: 0, fat: 13.5 },
    'fish sauce': { calories: 10, protein: 1.6, carbs: 0.7, fat: 0 },
    'oyster sauce': { calories: 9, protein: 0.3, carbs: 2, fat: 0 },
    'soy sauce': { calories: 9, protein: 1.3, carbs: 0.8, fat: 0.1 },
    'dark soy sauce': { calories: 11, protein: 1.5, carbs: 1.1, fat: 0 },
    'sesame oil': { calories: 120, protein: 0, carbs: 0, fat: 14 },
    'coconut milk': { basis: 'cup', calories: 445, protein: 4.6, carbs: 6.4, fat: 48 },
    miso: { calories: 34, protein: 2.2, carbs: 4.3, fat: 1.2 },
    gochujang: { calories: 33, protein: 0.9, carbs: 7.2, fat: 0.5 },
    'curry paste': { calories: 25, protein: 0.5, carbs: 3, fat: 1.2 },
    mirin: { calories: 35, protein: 0, carbs: 8, fat: 0 },
  }),
  ...createEntries('herbs_spices', [
    'cumin',
    'ground cumin',
    'coriander',
    'ground coriander',
    'turmeric',
    'paprika',
    'smoked paprika',
    'cayenne pepper',
    'black pepper',
    'white pepper',
    'red pepper flakes',
    'chili powder',
    'garam masala',
    'five spice powder',
    'allspice',
    'nutmeg',
    'cinnamon',
    'clove spice',
    'star anise',
    'cardamom',
    'fenugreek',
    'mustard seeds',
    'sesame seeds',
    'fennel seeds',
    'caraway seeds',
    'sumac',
    'zaatar',
    'saffron',
    'bay leaves',
    'dried oregano',
    'dried thyme',
    'dried basil',
    'dried rosemary',
    'garlic powder',
    'onion powder',
    'ginger powder',
    'celery salt',
    'sea salt',
    'kosher salt',
    'pink salt',
  ], {
    salt: { basis: 'tsp', calories: 0, protein: 0, carbs: 0, fat: 0 },
    pepper: { basis: 'tsp', calories: 6, protein: 0.2, carbs: 1.4, fat: 0.1 },
  }),
  ...createEntries('nuts_seeds', [
    'almonds',
    'walnuts',
    'pecans',
    'cashews',
    'pistachios',
    'hazelnuts',
    'macadamia nuts',
    'brazil nuts',
    'peanuts',
    'pine nuts',
    'chia seeds',
    'flax seeds',
    'pumpkin seeds',
    'sunflower seeds',
    'hemp seeds',
    'sesame seed paste',
    'almond butter',
    'peanut butter',
    'cashew butter',
    'tahini paste',
  ]),
  ...createEntries('baking', [
    'baking powder',
    'baking soda',
    'yeast',
    'corn syrup',
    'maple syrup',
    'molasses',
    'brown sugar',
    'powdered sugar',
    'coconut sugar',
    'vanilla extract',
    'cocoa powder',
    'dark chocolate',
    'milk chocolate',
    'white chocolate',
  ], {
    'baking powder': { basis: 'tsp', calories: 2, protein: 0, carbs: 0.8, fat: 0 },
    'baking soda': { basis: 'tsp', calories: 0, protein: 0, carbs: 0, fat: 0 },
    yeast: { basis: 'tbsp', calories: 23, protein: 3, carbs: 2, fat: 0.3 },
    sugar: { basis: 'tbsp', calories: 49, protein: 0, carbs: 12.6, fat: 0 },
  }),
  ...createEntries('beverages', [
    'orange juice',
    'apple juice',
    'pineapple juice',
    'grape juice',
    'lemon juice',
    'lime juice',
    'coconut water',
    'sparkling water',
    'black tea',
    'green tea',
    'coffee',
    'espresso',
    'kombucha',
    'almond beverage',
    'soy beverage',
    'oat beverage',
  ], {
    water: { basis: '100ml', calories: 0, protein: 0, carbs: 0, fat: 0 },
    broth: { basis: '100ml', calories: 6, protein: 0.5, carbs: 0.4, fat: 0.2 },
    juice: { basis: '100ml', calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2 },
  }),
}

const legacyCatalog = Object.fromEntries(
  Object.entries(LEGACY_INGREDIENT_NUTRITION).map(([key, nutrition]) => [
    key,
    {
      category: inferLegacyCategory(key),
      nutrition,
    },
  ])
) as Record<string, IngredientCatalogEntry>

export const INGREDIENT_CATALOG: Record<string, IngredientCatalogEntry> = {
  ...additionalCatalog,
  ...legacyCatalog,
}

export const INGREDIENT_NUTRITION: Record<string, IngredientNutrition> = Object.fromEntries(
  Object.entries(INGREDIENT_CATALOG).map(([key, entry]) => [key, entry.nutrition])
)

export const INGREDIENT_CATEGORIES: Record<string, IngredientCategory> = Object.fromEntries(
  Object.entries(INGREDIENT_CATALOG).map(([key, entry]) => [key, entry.category])
)

export function getSupportedIngredientKeys(): string[] {
  return Object.keys(INGREDIENT_NUTRITION).sort()
}

export function getIngredientCategoryCounts(): Record<IngredientCategory, number> {
  return Object.values(INGREDIENT_CATEGORIES).reduce<Record<IngredientCategory, number>>(
    (counts, category) => {
      counts[category] = (counts[category] ?? 0) + 1
      return counts
    },
    {
      proteins: 0,
      grains_starches: 0,
      vegetables: 0,
      legumes: 0,
      fruits: 0,
      dairy: 0,
      oils_sauces: 0,
      herbs_spices: 0,
      nuts_seeds: 0,
      baking: 0,
      beverages: 0,
      other: 0,
    }
  )
}
