#!/usr/bin/env node
/**
 * Regenerate src/types/database.ts from the linked Supabase project.
 *
 * Prerequisites:
 *   1. npm install (supabase CLI is a devDependency)
 *   2. npx supabase login   OR   export SUPABASE_ACCESS_TOKEN=...
 *   3. VITE_SUPABASE_URL in .env (used to derive project ref)
 *
 * Usage: npm run gen:types
 */
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const envPath = join(root, '.env')
const outPath = join(root, 'src/types/database.ts')
const isWindows = process.platform === 'win32'

function loadProjectRef() {
  const fromEnv = process.env.SUPABASE_PROJECT_REF?.trim()
  if (fromEnv) return fromEnv

  let envText = ''
  try {
    envText = readFileSync(envPath, 'utf8')
  } catch {
    throw new Error(
      'Missing .env. Set VITE_SUPABASE_URL or SUPABASE_PROJECT_REF before running gen:types.'
    )
  }

  const match = envText.match(
    /VITE_SUPABASE_URL=https:\/\/([a-z0-9-]+)\.supabase\.co/i
  )
  if (!match) {
    throw new Error(
      'Could not parse project ref from VITE_SUPABASE_URL. Set SUPABASE_PROJECT_REF manually.'
    )
  }

  return match[1]
}

/**
 * Resolve how to invoke the Supabase CLI cross-platform:
 * 1. node node_modules/supabase/dist/supabase.js (preferred — no shell)
 * 2. node_modules/.bin/supabase[.cmd]
 * 3. npx supabase
 */
function resolveSupabaseInvocation() {
  const require = createRequire(import.meta.url)

  try {
    const pkgPath = require.resolve('supabase/package.json')
    const cliPath = join(dirname(pkgPath), 'dist', 'supabase.js')

    if (existsSync(cliPath)) {
      return {
        command: process.execPath,
        args: [cliPath],
        shell: false,
      }
    }
  } catch {
    // supabase package not installed — fall through
  }

  const localBin = join(
    root,
    'node_modules',
    '.bin',
    isWindows ? 'supabase.cmd' : 'supabase'
  )

  if (existsSync(localBin)) {
    return {
      command: localBin,
      args: [],
      shell: isWindows,
    }
  }

  return {
    command: isWindows ? 'npx.cmd' : 'npx',
    args: ['supabase'],
    shell: isWindows,
  }
}

function runSupabase(args) {
  const { command, args: commandPrefix, shell } = resolveSupabaseInvocation()

  const result = spawnSync(command, [...commandPrefix, ...args], {
    cwd: root,
    encoding: 'utf8',
    shell,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: process.env,
  })

  if (result.error) {
    throw new Error(`Failed to run Supabase CLI: ${result.error.message}`)
  }

  if (result.status !== 0) {
    const details = [result.stderr, result.stdout]
      .filter(Boolean)
      .join('\n')
      .trim()

    throw new Error(
      details || `Supabase CLI exited with code ${result.status ?? 'unknown'}`
    )
  }

  return result.stdout ?? ''
}

const projectRef = loadProjectRef()

const generated = runSupabase([
  'gen',
  'types',
  'typescript',
  '--project-id',
  projectRef,
])

const banner = `/**
 * Supabase database types — generated by \`npm run gen:types\`.
 * Do not edit manually; regenerate after schema changes.
 *
 * Last generated for project: ${projectRef}
 */

`

writeFileSync(outPath, banner + generated.trim() + '\n', 'utf8')
console.log(`Wrote ${outPath} (${generated.length} bytes)`)
