-- Create saved_recipes table to persist user favorites across devices
-- After creating the table, run db/enable_rls_policies.sql in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.saved_recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id bigint NOT NULL REFERENCES public.recipes(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(recipe_id, user_id)
);

-- Optional: enable row level security and add policies allowing users to
-- manage their own saved recipes. Uncomment if you use RLS in your DB.

-- ALTER TABLE public.saved_recipes ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY "insert_own_saved" ON public.saved_recipes
--   FOR INSERT
--   WITH CHECK (auth.uid() = user_id);
--
-- CREATE POLICY "select_saved_authenticated" ON public.saved_recipes
--   FOR SELECT
--   USING (auth.uid() IS NOT NULL);
--
-- CREATE POLICY "delete_own_saved" ON public.saved_recipes
--   FOR DELETE
--   USING (auth.uid() = user_id);
